# Example cluster config for the networking template
clusterName: "example.com"
baseDomain: "example.com"
machinePrefixLength: 25
mastersScheduable: true
defaultGateway: "192.168.1.254"
openshiftVersion: '4.18.30'
#sno: true
pullSecret: ''
bmcEndpoint: ''
cpuArch: 'x86_64'
apiVip: '10.0.0.1'
ingressVip: '10.0.0.2'
networking:
  clusterNetwork:
    cidr: 10.10.10.1/23
    hostPrefix: 23
  machineNetwork:
    cidr: 192.168.1.0/24
  serviceNetwork:
    - 192.168.168.0/24
controlPlaneAgents: 1
sshPublicKey: ''
dnsServers:
  - <dnsIP1>
  - <dnsIP2>
  - <dnsIP3>
hosts:
  - name: host-1
    bmcUsername: 'root'
    bmcPassword: 'password'
    bootMACAddress: '00:11:22:33:44:55'
    interfaces: 
      - macAddress: ""
      - macAddress: ""
      - macAddress: ""
        name: "ens1f1p1"
    primaryMac: ""
    IP: <host-1-ip>
   # ... #
  - name: host-n
    bmcUsername: 'root'
    bmcPassword: 'password'
    bootMACAddress: '00:11:22:33:44:55'
    interfaces: 
      - macAddress: '"string; regex_match: [A-z0-9]{2}(:[A-z0-9]{2}){5}"'
      - macAddress: ""
      - macAddress: ""
        name: "ens2f1p2"
    useBond: true
    primaryMac: ""
    IP: <host-n-ip>
