# Example cluster config for the networking template
clusterName: "test-cluster"
baseDomain: "example.com"
machinePrefixLength: 25
defaultGateway: "<gateway-ip>"
openshiftVersion: '4.19.17'
bmcPrefix: 'redfish'
apiVip: '10.0.0.1'
ingressVip: '10.0.0.2'
pullSecret: ""
bmcEndpoint: '/redfish/v1/Systems/system.Embedded.1'
cpuArch: 'x86_64'
networking:
  clusterNetwork:
    cidr: 10.10.10.1/23
    hostPrefix: 23
  machineNetwork:
    cidr: 192.168.86.1/24
  serviceNetwork:
    - 192.168.87.1/24
controlPlaneAgents: 3
sshPublicKey: "test"
dnsServers:
  - <dnsIP1>
  - <dnsIP2>
  - <dnsIP3>
hosts:
  - name: host-1
    bmcUsername: 'root'
    bmcPassword: 'password'
    bmcEndpoint: '127.0.0.1'
    bootMACAddress: '00:11:22:33:44:55'
    interfaces: 
      - macAddress: ""
      - macAddress: ""
      - macAddress: ""
        name: "ens1f1p1"
    primaryMac: ""
    IP: <host-1-ip>
   # ... #
  - name: host-n
    bmcUsername: 'root'
    bmcPassword: 'password'
    bmcEndpoint: 'redfish://127.0.0.1/redfish/v1/Systems/System.Embedded.1'
    bootMACAddress: '00:11:22:33:44:55'
    interfaces: 
      - macAddress: '"string; regex_match: [A-z0-9]{2}(:[A-z0-9]{2}){5}"'
      - macAddress: ""
      - macAddress: ""
        name: "ens2f1p2"
    useBond: true
    primaryMac: ""
    IP: <host-n-ip>


