# Example cluster config for the networking template
clusterName: "test-cluster"
baseDomain: "example.com"
openshiftVersion: '4.19.17'
apiVip: '10.0.0.1'
ingressVip: '10.0.0.2'
# optional, defaults to false everywhere
pullSecret: ""
bmcPrefix: 'redfish-virtualmedia'
bmcEndpoint: '/redfish/v1/Systems/system.Embedded.1'
cpuArch: 'x86_64'
networking:
  machinePrefixLength: 25
  defaultGateway: "<gateway-ip>"
  clusterNetwork:
    cidr: 10.10.10.1/23
  machineNetwork:
    cidr: 192.168.86.1/24
  serviceNetwork:
    - 192.168.87.1/24
  dnsServers:
    - <dnsIP1>
    - <dnsIP2>
    - <dnsIP3>
controlPlaneAgents: 3
sshPublicKey: "test"
hosts:
  - name: host-1
    bmcUsername: 'root'
    bmcPassword: 'password'
    bmcIP: '192.168.86.1'
    bmcEndpoint: "/redfish/v1/Systems/SERIAL_NUMBER"
    bootMACAddress: '00:11:22:33:44:55'
    interfaces: 
      - macAddress: ""
      - macAddress: ""
      - macAddress: ""
        name: "ens1f1p1"
    primaryMac: ""
    IP: <host-1-ip>
   # ... #
  - name: host-n
    bmcUsername: 'root'
    bmcPassword: 'password'
    bootMACAddress: '00:11:22:33:44:55'
    interfaces: 
      - macAddress: '"string; regex_match: [A-z0-9]{2}(:[A-z0-9]{2}){5}"'
      - macAddress: ""
      - macAddress: ""
        name: "ens2f1p2"
    useBond: true
    primaryMac: ""
    IP: <host-n-ip>
